config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "sign-up", to: "registrations#new"
  post "sign-up", to: "registrations#create"
  get "sign-out", to: "authentications#destroy"
  get "sign-in", to: "authentications#new"
  post "sign-in", to: "authentications#create"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end

  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Thanks for signing in!"
      redirect_to root_path
    else
      flas[:notice] = "Oops something went wrong"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password))
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Thanks for signing up you are the best"
      redirect_to '/'
    else
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/new.html.haml
= form_tag sign_in_path do |f|
  = label_tag :email
  = text_field_tag :email

  = label_tag :password
  = password_field_tag :password

  = submit_tag "Sign in"


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserAuthentication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <%= link_to "Sign-Out", sign_out_path %>
  <% else %>
    <%= link_to "Sign me in!", sign_in_path %>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/static_pages/index.html.haml
Hello World

- if current_user
  Current User is:
  = current_user.email
-else
  Nobody is Here!!